import type {
  AuditLog,
  Battle,
  Brief,
  Category,
  Chat,
  Comment,
  ContentReport,
  Hub,
  Meme,
  Message,
  Notification,
  Person,
  PlatformControls,
  PointsTransaction,
  Post,
  Template,
  Tx,
  WithdrawalRequest,
  SystemConfigRecord,
} from "./types";

const now = Date.now();
const ago = (h: number, m = 0) => now - (h * 60 + m) * 60_000;
const days = (n: number) => now + n * 86_400_000;

export const YOU_ID = "you";

export const CATEGORIES: Category[] = [
  {
    id: "cat_relatable",
    name: "Relatable",
    slug: "relatable",
    description: "Everyday life, office struggles, student dilemmas & existential dread",
    icon: "😂",
    approvalPoints: 10,
    status: "active",
    sortOrder: 1,
    allowedTypes: "all",
    requiresReview: true,
    isDefault: true,
  },
  {
    id: "cat_dark",
    name: "Dark Humor",
    slug: "dark-humor",
    description: "Cynical wit, brutal truths & edgy comedy",
    icon: "💀",
    approvalPoints: 18,
    status: "active",
    sortOrder: 2,
  },
  {
    id: "cat_gaming",
    name: "Gaming",
    slug: "gaming",
    description: "Esports, clutch plays, GTA chaos & gamer rage",
    icon: "🎮",
    approvalPoints: 15,
    status: "active",
    sortOrder: 3,
  },
  {
    id: "cat_sports",
    name: "Sports & Cricket",
    slug: "sports",
    description: "IPL, last-ball thrillers, football banter & locker room moments",
    icon: "🏏",
    approvalPoints: 12,
    status: "active",
    sortOrder: 4,
  },
  {
    id: "cat_movies",
    name: "Movies & Cinema",
    slug: "movies",
    description: "Bollywood iconic lines, Hollywood spoilers & cinema gold",
    icon: "🎬",
    approvalPoints: 10,
    status: "active",
    sortOrder: 5,
  },
  {
    id: "cat_music",
    name: "Music & Beats",
    slug: "music",
    description: "Concert vibes, 3am headphone tracks & bassline culture",
    icon: "🎵",
    approvalPoints: 12,
    status: "active",
    sortOrder: 6,
  },
  {
    id: "cat_relationships",
    name: "Relationships",
    slug: "relationships",
    description: "Dating red flags, ghosting, situationships & wholesome moments",
    icon: "❤️",
    approvalPoints: 14,
    status: "active",
    sortOrder: 7,
  },
  {
    id: "cat_tech",
    name: "Tech & Dev",
    slug: "tech",
    description: "Bugs in prod, AI taking jobs, CSS struggle & 3am stack overflow",
    icon: "💻",
    approvalPoints: 20,
    status: "active",
    sortOrder: 8,
  },
  {
    id: "cat_food",
    name: "Food & Cravings",
    slug: "food",
    description: "Street food, midnight snacks, biryani debates & food coma",
    icon: "🍕",
    approvalPoints: 12,
    status: "active",
    sortOrder: 9,
  },
  {
    id: "cat_genz",
    name: "Gen-Z & Pop",
    slug: "gen-z",
    description: "Slang, brainrot, aesthetic vibes & fast internet culture",
    icon: "👀",
    approvalPoints: 10,
    status: "active",
    sortOrder: 10,
  },
  {
    id: "cat_india",
    name: "Desi & India",
    slug: "desi",
    description: "Indian family drama, local trains, monsoon chai & rishtedaar",
    icon: "🇮🇳",
    approvalPoints: 15,
    status: "active",
    sortOrder: 11,
  },
  {
    id: "cat_education",
    name: "Education & Exams",
    slug: "education",
    description: "All-nighters, viva panic, engineers & assignment deadlines",
    icon: "📚",
    approvalPoints: 25,
    status: "active",
    sortOrder: 12,
  },
  {
    id: "cat_animals",
    name: "Animals & Pets",
    slug: "animals",
    description: "Judgmental cats, confused dogs & animal chaos",
    icon: "🐶",
    approvalPoints: 10,
    status: "active",
    sortOrder: 13,
  },
];

export const TEMPLATES: Template[] = [
  { id: "cat", src: "/memes/cat.jpg", label: "Judge Cat" },
  { id: "dog", src: "/memes/dog.jpg", label: "Confused Dog" },
  { id: "food", src: "/memes/food.jpg", label: "Midnight Craving" },
  { id: "cricket", src: "/memes/cricket.jpg", label: "Last Ball Thriller" },
  { id: "sneaker", src: "/memes/sneaker.jpg", label: "The Sneaker Drop" },
  { id: "desk", src: "/memes/desk.jpg", label: "3AM Coding Desk" },
  { id: "club", src: "/memes/club.jpg", label: "After Hours Club" },
];

export const PEOPLE: Person[] = [
  {
    id: YOU_ID,
    handle: "abhishek",
    name: "Abhishek Gawade (Owner)",
    bio: "Platform Owner & Founder · RIFF Studio. Building the future of viral media.",
    role: "owner",
    followers: 12480,
    following: 482,
    mark: "you",
    instagramHandle: "abhishek_on_riff",
    creatorPopularity: 99400,
    riffPoints: 100,
    permissions: [
      "submission.review",
      "category.manage",
      "moderation.manage",
      "appeal.review",
      "campaign.manage",
      "withdrawal.review",
      "wallet.view",
      "audit.view",
      "staff.manage",
    ],
  },
  {
    id: "rahul",
    handle: "rahul",
    name: "Rahul Sharma",
    bio: "Memes & Gaming. Clutch king on weekends.",
    role: "creator",
    followers: 18900,
    following: 340,
    mark: "kabir",
    instagramHandle: "rahul_plays",
    creatorPopularity: 84300,
    riffPoints: 85,
  },
  {
    id: "aanya",
    handle: "aanya.riff",
    name: "Aanya Rao",
    bio: "Captions first, pixels second. Box-office and bassline.",
    role: "creator",
    followers: 18400,
    following: 290,
    mark: "aanya",
    instagramHandle: "aanyarao",
    creatorPopularity: 79200,
    riffPoints: 65,
  },
  {
    id: "kabir",
    handle: "kabir.lane",
    name: "Kabir Lane",
    bio: "Sports riffs & tech debugging. Last-ball specialist.",
    role: "creator",
    followers: 22100,
    following: 410,
    mark: "kabir",
    instagramHandle: "kabir_lane",
    creatorPopularity: 91400,
    riffPoints: 95,
  },
  {
    id: "mira",
    handle: "mira.ink",
    name: "Mira Sen",
    bio: "Street food, dark comedy & 3am desks.",
    role: "creator",
    followers: 9600,
    following: 180,
    mark: "mira",
    instagramHandle: "mira_ink",
    creatorPopularity: 64100,
    riffPoints: 50,
  },
  {
    id: "zane",
    handle: "zane.drop",
    name: "Zane Okoye",
    bio: "Sneakers, aesthetic reels and midnight decisions.",
    role: "creator",
    followers: 31200,
    following: 520,
    mark: "zane",
    instagramHandle: "zane_drop",
    creatorPopularity: 98500,
    riffPoints: 110,
  },
  {
    id: "priya",
    handle: "priya.loop",
    name: "Priya Malik",
    bio: "Soundtracks & club riffs. Sound on 🎧",
    role: "creator",
    followers: 14750,
    following: 310,
    mark: "priya",
    instagramHandle: "priya_loop",
    creatorPopularity: 72800,
    riffPoints: 60,
    warningsCount: 0,
    isBanned: false,
  },
  {
    id: "alex_admin",
    handle: "alex.admin",
    name: "Alex Varma",
    bio: "Category Moderator & Content Curator. Tech & Gaming lead.",
    role: "creator",
    followers: 24500,
    following: 120,
    mark: "zane",
    instagramHandle: "alex_admin",
    creatorPopularity: 89000,
    riffPoints: 125,
    warningsCount: 0,
    isBanned: false,
  },
  {
    id: "sarah_super",
    handle: "sarah.super",
    name: "Sarah SuperAdmin",
    bio: "Lead Governance & Platform Security. Oversees Category Compliance.",
    role: "creator",
    followers: 52000,
    following: 80,
    mark: "aanya",
    instagramHandle: "sarah_super",
    creatorPopularity: 112000,
    riffPoints: 210,
    warningsCount: 0,
    isBanned: false,
  },
];

export const INITIAL_POSTS: Post[] = [];

// Initial Pending Submissions for Admin Queue
export const INITIAL_PENDING_SUBMISSIONS: Post[] = [
  {
    id: "sub_1",
    authorId: "rahul",
    authorName: "Rahul Sharma",
    authorHandle: "rahul",
    authorAvatar: "/avatars/kabir.jpg",
    authorMark: "kabir",
    type: "post",
    mediaUrl: "/memes/dog.jpg",
    caption: "When you finally find the bug that was keeping prod down for 6 hours",
    topCaption: "FOUND THE BUG",
    bottomCaption: "IT WAS A MISSING COMMA",
    hashtags: ["#tech", "#devlife", "#coding"],
    userSelectedCategoryId: "cat_gaming", // Submitter selected Gaming by mistake!
    approvalStatus: "under_review",
    pointsAwarded: 0,
    likes: 0,
    views: 1,
    comments: 0,
    shares: 0,
    saves: 0,
    createdAt: ago(0, 25),
    popularityScore: 10,
  },
  {
    id: "sub_2",
    authorId: "mira",
    authorName: "Mira Sen",
    authorHandle: "mira.ink",
    authorAvatar: "/avatars/mira.jpg",
    authorMark: "mira",
    type: "reel",
    mediaUrl: "/memes/desk.jpg",
    caption: "3AM thesis writing vs my brain playing 2000s Bollywood songs on repeat 🇮🇳",
    topCaption: "THESIS DEADLINE IN 4 HOURS",
    bottomCaption: "MY BRAIN: DHOOM MACHALE 🎵",
    hashtags: ["#desi", "#education", "#studentlife"],
    userSelectedCategoryId: "cat_india",
    approvalStatus: "under_review",
    pointsAwarded: 0,
    likes: 0,
    views: 1,
    comments: 0,
    shares: 0,
    saves: 0,
    createdAt: ago(1, 10),
    popularityScore: 15,
    aspectRatio: "9:16",
    musicTrack: { title: "Dhoom Nostalgia Riff", artist: "DesiBeats", isTrending: true },
  },
  {
    id: "sub_3",
    authorId: "zane",
    authorName: "Zane Okoye",
    authorHandle: "zane.drop",
    authorAvatar: "/avatars/zane.jpg",
    authorMark: "zane",
    type: "post",
    mediaUrl: "/memes/cat.jpg",
    caption: "My bank manager calling me after seeing 14 food delivery transactions in 2 days",
    topCaption: "BANK MANAGER:",
    bottomCaption: "ARE YOU OKAY SIR?",
    hashtags: ["#darkhumor", "#broke", "#food"],
    userSelectedCategoryId: "cat_dark",
    approvalStatus: "under_review",
    pointsAwarded: 0,
    likes: 0,
    views: 1,
    comments: 0,
    shares: 0,
    saves: 0,
    createdAt: ago(2, 5),
    popularityScore: 8,
  },
];

// Initial Rejected Submissions History for Moderation Audit
export const INITIAL_REJECTED_SUBMISSIONS: Post[] = [
  {
    id: "rej_1",
    authorId: "kabir",
    authorName: "Kabir Lane",
    authorHandle: "kabir.lane",
    authorAvatar: "/avatars/kabir.jpg",
    authorMark: "kabir",
    type: "post",
    mediaUrl: "/memes/cat.jpg",
    caption: "Low resolution blurry repost from external watermark site",
    hashtags: ["#sports", "#repost"],
    userSelectedCategoryId: "cat_sports",
    approvalStatus: "rejected",
    rejectionReason: "Low effort / watermark / spam",
    reviewedBy: "admin",
    reviewedAt: ago(5, 0),
    pointsAwarded: 0,
    likes: 0,
    views: 0,
    comments: 0,
    shares: 0,
    saves: 0,
    createdAt: ago(6, 0),
    popularityScore: 0,
  },
];

// Initial Removed Content Archive for Moderation Compliance & Transparency
export const INITIAL_REMOVED_SUBMISSIONS: Post[] = [
  {
    id: "rem_1",
    authorId: "zane",
    authorName: "Zane Okoye",
    authorHandle: "zane.drop",
    authorAvatar: "/avatars/zane.jpg",
    authorMark: "zane",
    type: "post",
    mediaUrl: "/memes/dog.jpg",
    caption: "Spam giveaway with external link in watermark",
    hashtags: ["#giveaway", "#promo", "#spam"],
    userSelectedCategoryId: "cat_relatable",
    approvedCategoryId: "cat_relatable",
    approvalStatus: "removed",
    rejectionReason: "Content removed following user report #rep_3: Community safety violation regarding misleading links",
    reviewedBy: "alex.admin",
    reviewedAt: ago(3, 45),
    pointsAwarded: 0,
    likes: 12,
    views: 320,
    comments: 2,
    shares: 0,
    saves: 0,
    createdAt: ago(7, 30),
    popularityScore: 0,
  },
];

export const INITIAL_COMMENTS: Comment[] = [];

export const INITIAL_POINTS_TXS: PointsTransaction[] = [];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: "audit_1",
    actorId: "admin",
    actorRole: "admin",
    action: "approve",
    postId: "post_1",
    postCaption: "Me waiting for salary on Monday morning...",
    submitterHandle: "you",
    userSelectedCategory: "Tech & Dev",
    approvedCategory: "Tech & Dev",
    pointsAwarded: 20,
    reason: "High quality original meme matching category guidelines",
    timestamp: ago(2, 30),
  },
  {
    id: "audit_2",
    actorId: "admin",
    actorRole: "admin",
    action: "change_category",
    postId: "post_2",
    postCaption: "When your teammate goes AFK during 1v3 clutch...",
    submitterHandle: "rahul",
    userSelectedCategory: "Relatable",
    approvedCategory: "Gaming",
    pointsAwarded: 15,
    reason: "Reclassified from Relatable to Gaming for optimal feed discovery",
    timestamp: ago(4, 15),
  },
  {
    id: "audit_3",
    actorId: "alex.admin",
    actorRole: "admin",
    action: "reject",
    postId: "rej_1",
    postCaption: "Low resolution blurry repost from external watermark site",
    submitterHandle: "kabir.lane",
    userSelectedCategory: "Sports",
    approvedCategory: "Rejected",
    pointsAwarded: 0,
    reason: "Low effort / watermark / spam: Unoriginal cropped screenshot",
    timestamp: ago(5, 0),
  },
  {
    id: "audit_4",
    actorId: "alex.admin",
    actorRole: "admin",
    action: "report_actioned",
    postId: "rem_1",
    postCaption: "Spam giveaway with external link in watermark",
    submitterHandle: "zane.drop",
    userSelectedCategory: "Relatable",
    approvedCategory: "Removed",
    pointsAwarded: 0,
    reason: "Content removed following user report #rep_3: Community safety violation regarding misleading links",
    timestamp: ago(3, 45),
  },
  {
    id: "audit_5",
    actorId: "alex.admin",
    actorRole: "admin",
    action: "report_dismissed",
    postId: "post_3",
    postCaption: "The group chat at 2:00 AM asking existential questions...",
    submitterHandle: "aanya.riff",
    userSelectedCategory: "Dark Humor",
    approvedCategory: "Dark Humor",
    pointsAwarded: 0,
    reason: "Report #rep_2 dismissed: Flagged content strictly adheres to community standards for satire",
    timestamp: ago(2, 0),
  },
  {
    id: "audit_6",
    actorId: "you",
    actorRole: "owner",
    action: "issue_warning",
    postId: "rem_1",
    postCaption: "Spam giveaway with external link in watermark",
    submitterHandle: "zane.drop",
    userSelectedCategory: "N/A",
    approvedCategory: "N/A",
    pointsAwarded: 0,
    reason: "Official strike 1/5: Posting external suspicious promotional links",
    timestamp: ago(3, 40),
  },
  {
    id: "audit_7",
    actorId: "you",
    actorRole: "owner",
    action: "create_category",
    userSelectedCategory: "Anime & Manga",
    approvedCategory: "Anime & Manga",
    pointsAwarded: 15,
    reason: "Created new official category 'Anime & Manga' with +15 RIFF Points reward",
    timestamp: ago(24, 0),
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [];

// Backwards compatibility data exports for legacy components
export const HUBS: Hub[] = [
  {
    id: "pavilion",
    name: "Pavilion",
    tag: "Sport",
    category: "Cricket",
    cover: "/memes/cricket.jpg",
    members: 128400,
    bio: "Floodlights, last balls, and the cousin who always bowls the death over.",
  },
  {
    id: "bassline",
    name: "Bassline",
    tag: "Music",
    category: "Clubs",
    cover: "/memes/club.jpg",
    members: 86200,
    bio: "Booths, bass, and the lie that you would leave at eleven.",
  },
  {
    id: "drop",
    name: "Drop",
    tag: "Style",
    category: "Streetwear",
    cover: "/memes/sneaker.jpg",
    members: 91000,
    bio: "Original colorways, wet asphalt, and a savings account that never stood a chance.",
  },
  {
    id: "late-shift",
    name: "Late Shift",
    tag: "Work",
    category: "Creators",
    cover: "/memes/desk.jpg",
    members: 54000,
    bio: "Sticky notes, MIDI, and the quick tweak that ate the night.",
  },
  {
    id: "tandoor",
    name: "Tandoor",
    tag: "Food",
    category: "Street",
    cover: "/memes/food.jpg",
    members: 77300,
    bio: "Griddles, steam, and the salad day that never survives the stall.",
  },
  {
    id: "menagerie",
    name: "Menagerie",
    tag: "Comedy",
    category: "Animals",
    cover: "/memes/cat.jpg",
    members: 156000,
    bio: "Judgmental cats, confused dogs, and the group chat at 2am.",
  },
];

export const MEMES: Meme[] = [
  {
    id: "m1",
    authorId: "aanya",
    hubId: "menagerie",
    image: "/memes/cat.jpg",
    top: "THE GROUP CHAT AT 2AM",
    bottom: "ME: ANYONE UP",
    likes: 4280,
    remixes: 312,
    comments: 2,
    createdAt: ago(1, 12),
    heat: 94,
  },
  {
    id: "m2",
    authorId: "kabir",
    hubId: "pavilion",
    image: "/memes/cricket.jpg",
    top: "12 NEEDED OFF 1",
    bottom: "BOWLER IS MY INTERN",
    likes: 8900,
    remixes: 640,
    comments: 1,
    createdAt: ago(3, 40),
    heat: 99,
  },
  {
    id: "m3",
    authorId: "mira",
    hubId: "tandoor",
    image: "/memes/food.jpg",
    top: "IT IS A SALAD DAY",
    bottom: "UNTIL IT IS NOT",
    likes: 2610,
    remixes: 188,
    comments: 1,
    createdAt: ago(5, 5),
    heat: 81,
  },
  {
    id: "m4",
    authorId: "zane",
    hubId: "drop",
    image: "/memes/sneaker.jpg",
    top: "MY SAVINGS",
    bottom: "THE DROP AT MIDNIGHT",
    likes: 6740,
    remixes: 401,
    comments: 1,
    createdAt: ago(8, 20),
    heat: 90,
  },
];

export const COMMENTS: Comment[] = INITIAL_COMMENTS;

export const BRIEFS: Brief[] = [];

export const CHATS: Chat[] = [];

export const MESSAGES: Message[] = [];

export const STARTER_TX: Tx[] = [];

export const BATTLE: Battle = {
  id: "bt1",
  leftId: "",
  rightId: "",
  leftVotes: 0,
  rightVotes: 0,
};

export const personMap = Object.fromEntries(PEOPLE.map((p) => [p.id, p])) as Record<string, Person>;
export const hubMap = Object.fromEntries(HUBS.map((h) => [h.id, h])) as Record<string, Hub>;
export const briefMap = Object.fromEntries(BRIEFS.map((b) => [b.id, b])) as Record<string, Brief>;
export const templateMap = Object.fromEntries(TEMPLATES.map((t) => [t.id, t])) as Record<string, Template>;
export const categoryMap = Object.fromEntries(CATEGORIES.map((c) => [c.id, c])) as Record<string, Category>;

export const INITIAL_REPORTS: ContentReport[] = [];

export const DEFAULT_PLATFORM_CONTROLS: PlatformControls = {
  maintenanceMode: false,
  submissionsPaused: false,
  renderFarmEcoMode: false,
  emergencyWalletFreeze: false,
  aiModerationSensitivity: "balanced",
  pointConversionRate: 0.5, // ₹0.50 per point
  minWithdrawalThreshold: 25, // ₹25 (50 points minimum)
  maxDailyWithdrawalLimit: 5000, // ₹5,000
  payoutProcessingFeePercent: 2, // 2%
};

export const INITIAL_WITHDRAWALS: WithdrawalRequest[] = [
  {
    id: "wth_101",
    userId: "rahul",
    userHandle: "rahul",
    userName: "Rahul Sharma",
    amount: 1500,
    pointsEquivalent: 3000,
    paymentMethod: "upi",
    paymentDetails: {
      upiId: "rahul.sharma@okaxis",
      holderName: "Rahul Sharma",
    },
    status: "pending",
    createdAt: ago(3, 15),
    idempotencyKey: "withdrawal:wth_101",
  },
  {
    id: "wth_102",
    userId: "zane",
    userHandle: "zane.drop",
    userName: "Zane Okoye",
    amount: 2000,
    pointsEquivalent: 4000,
    paymentMethod: "bank_transfer",
    paymentDetails: {
      accountNumber: "918273645012",
      ifsc: "HDFC0001234",
      holderName: "Zane Okoye",
    },
    status: "pending",
    createdAt: ago(1, 45),
    idempotencyKey: "withdrawal:wth_102",
  },
  {
    id: "wth_103",
    userId: "aanya",
    userHandle: "aanya.riff",
    userName: "Aanya Rao",
    amount: 1000,
    pointsEquivalent: 2000,
    paymentMethod: "upi",
    paymentDetails: {
      upiId: "aanya@icici",
      holderName: "Aanya Rao",
    },
    status: "completed",
    createdAt: ago(24, 0),
    processedAt: ago(20, 0),
    idempotencyKey: "withdrawal:wth_103",
  },
  {
    id: "wth_104",
    userId: "mira",
    userHandle: "mira.ink",
    userName: "Mira Sen",
    amount: 800,
    pointsEquivalent: 1600,
    paymentMethod: "upi",
    paymentDetails: {
      upiId: "mira@invalidupi",
      holderName: "Mira Sen",
    },
    status: "failed",
    createdAt: ago(48, 0),
    processedAt: ago(47, 30),
    adminNote: "UPI ID rejected by clearing house (VPA not found)",
    idempotencyKey: "withdrawal:wth_104",
  },
];

export const INITIAL_SYSTEM_CONFIGS: SystemConfigRecord[] = [
  // Platform
  {
    id: "cfg_maintenance_mode",
    key: "maintenance_mode",
    value: "false",
    valueType: "boolean",
    category: "platform",
    description: "When enabled, normal users see a maintenance screen and non-administrative API mutations are paused. Staff retain bypass access.",
    isPublic: true,
    updatedBy: "system",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "cfg_new_registrations_enabled",
    key: "new_registrations_enabled",
    value: "true",
    valueType: "boolean",
    category: "platform",
    description: "Controls whether new creator and visitor account registrations are accepted.",
    isPublic: true,
    updatedBy: "system",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "cfg_platform_enabled",
    key: "platform_enabled",
    value: "true",
    valueType: "boolean",
    category: "platform",
    description: "Master platform availability toggle for creator feed, reels studio, and social actions.",
    isPublic: true,
    updatedBy: "system",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  // Content
  {
    id: "cfg_max_upload_size_mb",
    key: "max_upload_size_mb",
    value: "100",
    valueType: "integer",
    category: "content",
    description: "Maximum allowed media file size in megabytes (MB) for uploads.",
    isPublic: true,
    updatedBy: "system",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "cfg_max_reel_duration_seconds",
    key: "max_reel_duration_seconds",
    value: "180",
    valueType: "integer",
    category: "content",
    description: "Maximum duration in seconds allowed for Reel Studio exports.",
    isPublic: true,
    updatedBy: "system",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "cfg_max_post_images",
    key: "max_post_images",
    value: "10",
    valueType: "integer",
    category: "content",
    description: "Maximum number of images allowed per post or carousel.",
    isPublic: true,
    updatedBy: "system",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "cfg_max_caption_length",
    key: "max_caption_length",
    value: "2200",
    valueType: "integer",
    category: "content",
    description: "Maximum character limit for captions across memes and reels.",
    isPublic: true,
    updatedBy: "system",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "cfg_allowed_media_types",
    key: "allowed_media_types",
    value: JSON.stringify(["image/jpeg", "image/png", "image/webp", "image/gif", "video/mp4", "video/webm"]),
    valueType: "json",
    category: "content",
    description: "Whitelist of permitted MIME media types for media upload.",
    isPublic: true,
    updatedBy: "system",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  // Moderation
  {
    id: "cfg_default_submission_status",
    key: "default_submission_status",
    value: "pending",
    valueType: "string",
    category: "moderation",
    description: "Initial moderation review status for new submissions (pending or approved).",
    isPublic: false,
    updatedBy: "system",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "cfg_auto_review_enabled",
    key: "auto_review_enabled",
    value: "false",
    valueType: "boolean",
    category: "moderation",
    description: "Automatically review and score submissions with perceptual hashing and text safety.",
    isPublic: false,
    updatedBy: "system",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "cfg_auto_review_threshold",
    key: "auto_review_threshold",
    value: "0.85",
    valueType: "decimal",
    category: "moderation",
    description: "Confidence threshold (0.0 to 1.0) required for AI auto-approval.",
    isPublic: false,
    updatedBy: "system",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "cfg_report_threshold",
    key: "report_threshold",
    value: "5",
    valueType: "integer",
    category: "moderation",
    description: "Number of community reports before content is elevated to high-priority review queue.",
    isPublic: false,
    updatedBy: "system",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "cfg_auto_hide_report_threshold",
    key: "auto_hide_report_threshold",
    value: "10",
    valueType: "integer",
    category: "moderation",
    description: "Number of unique user reports that triggers automatic temporary content hiding pending review.",
    isPublic: false,
    updatedBy: "system",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  // Economy
  {
    id: "cfg_riff_points_enabled",
    key: "riff_points_enabled",
    value: "true",
    valueType: "boolean",
    category: "economy",
    description: "Global toggle for RIFF Points reward distributions and points balances.",
    isPublic: true,
    updatedBy: "system",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "cfg_points_per_approved_post",
    key: "points_per_approved_post",
    value: "10",
    valueType: "integer",
    category: "economy",
    description: "Default RIFF points awarded when a meme post is approved (if category has no custom points).",
    isPublic: true,
    updatedBy: "system",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "cfg_points_per_approved_reel",
    key: "points_per_approved_reel",
    value: "25",
    valueType: "integer",
    category: "economy",
    description: "Default RIFF points awarded when a reel is approved (if category has no custom points).",
    isPublic: true,
    updatedBy: "system",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "cfg_minimum_withdrawal_points",
    key: "minimum_withdrawal_points",
    value: "1000",
    valueType: "integer",
    category: "economy",
    description: "Minimum RIFF Points balance required to request a payout.",
    isPublic: true,
    updatedBy: "system",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "cfg_maximum_withdrawal_points",
    key: "maximum_withdrawal_points",
    value: "100000",
    valueType: "integer",
    category: "economy",
    description: "Maximum RIFF Points that can be requested in a single payout transaction.",
    isPublic: true,
    updatedBy: "system",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "cfg_daily_withdrawal_limit",
    key: "daily_withdrawal_limit",
    value: "100000",
    valueType: "integer",
    category: "economy",
    description: "Maximum cumulative RIFF Points a creator can withdraw within a rolling 24-hour window.",
    isPublic: true,
    updatedBy: "system",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "cfg_creator_reward_enabled",
    key: "creator_reward_enabled",
    value: "true",
    valueType: "boolean",
    category: "economy",
    description: "Global switch allowing creators to convert points into monetary payout requests.",
    isPublic: true,
    updatedBy: "system",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  // Notifications
  {
    id: "cfg_push_notifications_enabled",
    key: "push_notifications_enabled",
    value: "true",
    valueType: "boolean",
    category: "notifications",
    description: "Enables web push and browser notification delivery.",
    isPublic: false,
    updatedBy: "system",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "cfg_email_notifications_enabled",
    key: "email_notifications_enabled",
    value: "true",
    valueType: "boolean",
    category: "notifications",
    description: "Enables transactional and contest alert email dispatches.",
    isPublic: false,
    updatedBy: "system",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "cfg_notification_batching_enabled",
    key: "notification_batching_enabled",
    value: "true",
    valueType: "boolean",
    category: "notifications",
    description: "Batches high-frequency social notifications into digest summaries.",
    isPublic: false,
    updatedBy: "system",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  // Security
  {
    id: "cfg_session_duration_hours",
    key: "session_duration_hours",
    value: "168",
    valueType: "integer",
    category: "security",
    description: "Active user session duration in hours before re-authentication is required.",
    isPublic: false,
    updatedBy: "system",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "cfg_login_rate_limit",
    key: "login_rate_limit",
    value: "10",
    valueType: "integer",
    category: "security",
    description: "Maximum login attempts per IP/handle per 15-minute window before throttling.",
    isPublic: false,
    updatedBy: "system",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "cfg_otp_rate_limit",
    key: "otp_rate_limit",
    value: "5",
    valueType: "integer",
    category: "security",
    description: "Maximum OTP verification attempts per phone/email per 10-minute window.",
    isPublic: false,
    updatedBy: "system",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "cfg_password_attempt_limit",
    key: "password_attempt_limit",
    value: "5",
    valueType: "integer",
    category: "security",
    description: "Maximum failed password attempts before account lock.",
    isPublic: false,
    updatedBy: "system",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "cfg_suspicious_login_detection_enabled",
    key: "suspicious_login_detection_enabled",
    value: "true",
    valueType: "boolean",
    category: "security",
    description: "Flag and challenge logins from new IP addresses or uncommon geo-locations.",
    isPublic: false,
    updatedBy: "system",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
];

