import type {
  EditorProject,
  VideoClip,
  TextTrackItem,
  AudioTrackItem,
  StickerTrackItem,
  EffectTrackItem,
  CaptionItem,
} from "./types";
import { PRESET_MUSIC_TRACKS } from "./audio-engine";

export type StudioTemplate = {
  id: string;
  name: string;
  category: "trending" | "meme" | "gaming" | "cinematic" | "indian" | "story";
  icon: string;
  description: string;
  previewThumbnail: string;
  duration: number;
  project: Omit<EditorProject, "id" | "updatedAt">;
};

export const STOCK_SCENES = [
  { id: "desk", label: "Work Desk / Office", src: "/memes/desk.jpg", mood: "relatable" },
  { id: "cricket", label: "Stadium Cricket Match", src: "/memes/cricket.jpg", mood: "hype" },
  { id: "club", label: "Neon Nightclub Party", src: "/memes/club.jpg", mood: "trending" },
  { id: "cat", label: "Shocked Cat Meme", src: "/memes/cat.jpg", mood: "funny" },
  { id: "dog", label: "Cool Dog Shades", src: "/memes/dog.jpg", mood: "meme" },
  { id: "food", label: "Street Food Feast", src: "/memes/food.jpg", mood: "desi" },
  { id: "sneaker", label: "Hype Sneakers Drop", src: "/memes/sneaker.jpg", mood: "aesthetic" },
];

export const STUDIO_TEMPLATES: StudioTemplate[] = [
  {
    id: "tmpl_trending_phonk",
    name: "🔥 Trending Phonk Drift",
    category: "trending",
    icon: "🔥",
    description: "High-octane beat drop, cyber glow LUT, fast zooms & karaoke subtitle sync.",
    previewThumbnail: "/memes/club.jpg",
    duration: 12.0,
    project: {
      title: "Trending Phonk Reel",
      aspectRatio: "9:16",
      duration: 12.0,
      clips: [
        {
          id: "clip_1",
          name: "Intro Hook",
          sourceUrl: "/memes/club.jpg",
          mediaType: "image",
          duration: 3.5,
          sourceStart: 0,
          sourceEnd: 3.5,
          timelineStart: 0,
          timelineEnd: 3.5,
          speed: 1.0,
          volume: 100,
          muted: false,
          rotation: 0,
          transitionIn: { type: "flash", duration: 0.4 },
        },
        {
          id: "clip_2",
          name: "The Beat Drop",
          sourceUrl: "/memes/sneaker.jpg",
          mediaType: "image",
          duration: 4.5,
          sourceStart: 0,
          sourceEnd: 4.5,
          timelineStart: 3.5,
          timelineEnd: 8.0,
          speed: 1.25,
          volume: 100,
          muted: false,
          rotation: 0,
          transitionIn: { type: "zoom", duration: 0.5 },
        },
        {
          id: "clip_3",
          name: "Climax Finale",
          sourceUrl: "/memes/desk.jpg",
          mediaType: "image",
          duration: 4.0,
          sourceStart: 0,
          sourceEnd: 4.0,
          timelineStart: 8.0,
          timelineEnd: 12.0,
          speed: 1.0,
          volume: 100,
          muted: false,
          rotation: 0,
          transitionIn: { type: "glitch", duration: 0.4 },
        },
      ],
      audioTracks: [
        {
          id: "aud_phonk",
          title: PRESET_MUSIC_TRACKS[0].title,
          artist: PRESET_MUSIC_TRACKS[0].artist,
          type: "music",
          sourceUrl: "synth:phonk",
          timelineStart: 0,
          duration: 12.0,
          volume: 85,
          muted: false,
          fadeIn: false,
          fadeOut: true,
          beats: PRESET_MUSIC_TRACKS[0].beats,
          isTrending: true,
        },
      ],
      textLayers: [
        {
          id: "txt_hook",
          text: "WAIT FOR THE DROP... ⚡",
          timelineStart: 0.5,
          timelineEnd: 3.2,
          x: 50,
          y: 25,
          fontFamily: "Display",
          fontSize: 22,
          color: "#00F0FF",
          strokeColor: "#000000",
          strokeWidth: 4,
          animation: "pop",
          style: "neon",
        },
        {
          id: "txt_hype",
          text: "ABSOLUTE CINEMA 🎬",
          timelineStart: 4.0,
          timelineEnd: 7.5,
          x: 50,
          y: 75,
          fontFamily: "Impact",
          fontSize: 26,
          color: "#FFFFFF",
          strokeColor: "#000000",
          strokeWidth: 5,
          animation: "glitch",
          style: "meme_impact",
        },
      ],
      stickers: [
        {
          id: "stk_fire",
          emojiOrUrl: "🔥",
          type: "emoji",
          timelineStart: 3.5,
          timelineEnd: 7.0,
          x: 80,
          y: 30,
          scale: 1.4,
          rotation: 12,
          animation: "bounce",
        },
      ],
      effects: [
        {
          id: "fx_glitch",
          effect: "glitch",
          timelineStart: 3.2,
          timelineEnd: 4.2,
          intensity: 80,
        },
      ],
      captions: [
        {
          id: "cap_1",
          text: "Bhai yeh drop suno ek baar...",
          timelineStart: 0.5,
          timelineEnd: 3.2,
          words: [
            { word: "Bhai", start: 0.5, end: 1.0 },
            { word: "yeh", start: 1.0, end: 1.5 },
            { word: "drop", start: 1.5, end: 2.2 },
            { word: "suno...", start: 2.2, end: 3.2 },
          ],
        },
        {
          id: "cap_2",
          text: "Pura game change ho gaya! 🚀",
          timelineStart: 3.5,
          timelineEnd: 7.0,
          words: [
            { word: "Pura", start: 3.5, end: 4.2 },
            { word: "game", start: 4.2, end: 5.0 },
            { word: "change!", start: 5.0, end: 6.8 },
          ],
        },
      ],
      adjustments: {
        brightness: 105,
        contrast: 120,
        saturation: 125,
        exposure: 5,
        temperature: -10,
        vignette: 25,
        filterPreset: "cyber_glow",
      },
      memeMode: false,
      memeTopText: "",
      memeBottomText: "",
    },
  },
  {
    id: "tmpl_relatable_meme",
    name: "😂 Relatable Meme Mode",
    category: "meme",
    icon: "😂",
    description: "Classic top & bottom Impact font punchline with Vine boom SFX & zoom in.",
    previewThumbnail: "/memes/desk.jpg",
    duration: 8.0,
    project: {
      title: "Relatable Office Meme",
      aspectRatio: "9:16",
      duration: 8.0,
      clips: [
        {
          id: "clip_m1",
          name: "The Expectation",
          sourceUrl: "/memes/desk.jpg",
          mediaType: "image",
          duration: 4.0,
          sourceStart: 0,
          sourceEnd: 4.0,
          timelineStart: 0,
          timelineEnd: 4.0,
          speed: 1.0,
          volume: 100,
          muted: false,
          rotation: 0,
        },
        {
          id: "clip_m2",
          name: "The Reality Punch",
          sourceUrl: "/memes/cat.jpg",
          mediaType: "image",
          duration: 4.0,
          sourceStart: 0,
          sourceEnd: 4.0,
          timelineStart: 4.0,
          timelineEnd: 8.0,
          speed: 1.0,
          volume: 100,
          muted: false,
          rotation: 0,
          transitionIn: { type: "zoom", duration: 0.3 },
        },
      ],
      audioTracks: [
        {
          id: "aud_sfx_boom",
          title: "Vine Boom",
          artist: "SFX",
          type: "sfx",
          sourceUrl: "sfx:boom",
          timelineStart: 4.0,
          duration: 0.8,
          volume: 100,
          muted: false,
          fadeIn: false,
          fadeOut: false,
        },
      ],
      textLayers: [],
      stickers: [
        {
          id: "stk_skull",
          emojiOrUrl: "💀",
          type: "emoji",
          timelineStart: 4.0,
          timelineEnd: 8.0,
          x: 50,
          y: 50,
          scale: 1.8,
          rotation: 0,
          animation: "bounce",
        },
      ],
      effects: [
        {
          id: "fx_shake",
          effect: "shake",
          timelineStart: 4.0,
          timelineEnd: 4.6,
          intensity: 75,
        },
      ],
      captions: [],
      adjustments: {
        brightness: 100,
        contrast: 110,
        saturation: 105,
        exposure: 0,
        temperature: 0,
        vignette: 15,
        filterPreset: "meme",
      },
      memeMode: true,
      memeTopText: "MANAGER: 'QUICK 5 MIN SYNC'",
      memeBottomText: "3 HOURS LATER IN THE CALL 💀",
    },
  },
  {
    id: "tmpl_gaming_clutch",
    name: "🎮 Gaming Clutch Highlight",
    category: "gaming",
    icon: "🎮",
    description: "Glitch effects, slow-mo 0.5x clutch moment, shake & bass drops.",
    previewThumbnail: "/memes/club.jpg",
    duration: 10.0,
    project: {
      title: "Gaming Clutch Montage",
      aspectRatio: "9:16",
      duration: 10.0,
      clips: [
        {
          id: "clip_g1",
          name: "Setup Rush",
          sourceUrl: "/memes/club.jpg",
          mediaType: "image",
          duration: 4.0,
          sourceStart: 0,
          sourceEnd: 4.0,
          timelineStart: 0,
          timelineEnd: 4.0,
          speed: 1.5,
          volume: 100,
          muted: false,
          rotation: 0,
        },
        {
          id: "clip_g2",
          name: "Slow Motion Clutch",
          sourceUrl: "/memes/sneaker.jpg",
          mediaType: "image",
          duration: 6.0,
          sourceStart: 0,
          sourceEnd: 6.0,
          timelineStart: 4.0,
          timelineEnd: 10.0,
          speed: 0.5,
          volume: 100,
          muted: false,
          rotation: 0,
          transitionIn: { type: "flash", duration: 0.3 },
        },
      ],
      audioTracks: [
        {
          id: "aud_bass",
          title: PRESET_MUSIC_TRACKS[3].title,
          artist: PRESET_MUSIC_TRACKS[3].artist,
          type: "music",
          sourceUrl: "synth:bass",
          timelineStart: 0,
          duration: 10.0,
          volume: 90,
          muted: false,
          fadeIn: false,
          fadeOut: true,
          beats: PRESET_MUSIC_TRACKS[3].beats,
        },
      ],
      textLayers: [
        {
          id: "txt_1v4",
          text: "1 HP CLUTCH GOD 🏆",
          timelineStart: 4.0,
          timelineEnd: 9.0,
          x: 50,
          y: 20,
          fontFamily: "Display",
          fontSize: 24,
          color: "#10B981",
          strokeColor: "#000000",
          strokeWidth: 4,
          animation: "pop",
          style: "neon",
        },
      ],
      stickers: [],
      effects: [
        {
          id: "fx_rgb",
          effect: "rgb_split",
          timelineStart: 4.0,
          timelineEnd: 5.5,
          intensity: 85,
        },
      ],
      captions: [],
      adjustments: {
        brightness: 110,
        contrast: 130,
        saturation: 120,
        exposure: 10,
        temperature: -5,
        vignette: 30,
        filterPreset: "cinematic",
      },
      memeMode: false,
      memeTopText: "",
      memeBottomText: "",
    },
  },
  {
    id: "tmpl_cinematic_35mm",
    name: "🎬 Cinematic 35mm Film",
    category: "cinematic",
    icon: "🎬",
    description: "Vintage film LUT, smooth crossfades, letterbox & chill lofi vibe.",
    previewThumbnail: "/memes/food.jpg",
    duration: 12.0,
    project: {
      title: "Cinematic Film 35mm",
      aspectRatio: "9:16",
      duration: 12.0,
      clips: [
        {
          id: "clip_c1",
          name: "Scene 1",
          sourceUrl: "/memes/food.jpg",
          mediaType: "image",
          duration: 6.0,
          sourceStart: 0,
          sourceEnd: 6.0,
          timelineStart: 0,
          timelineEnd: 6.0,
          speed: 1.0,
          volume: 100,
          muted: false,
          rotation: 0,
        },
        {
          id: "clip_c2",
          name: "Scene 2",
          sourceUrl: "/memes/desk.jpg",
          mediaType: "image",
          duration: 6.0,
          sourceStart: 0,
          sourceEnd: 6.0,
          timelineStart: 6.0,
          timelineEnd: 12.0,
          speed: 1.0,
          volume: 100,
          muted: false,
          rotation: 0,
          transitionIn: { type: "fade", duration: 0.8 },
        },
      ],
      audioTracks: [
        {
          id: "aud_lofi",
          title: PRESET_MUSIC_TRACKS[1].title,
          artist: PRESET_MUSIC_TRACKS[1].artist,
          type: "music",
          sourceUrl: "synth:lofi",
          timelineStart: 0,
          duration: 12.0,
          volume: 75,
          muted: false,
          fadeIn: true,
          fadeOut: true,
          beats: PRESET_MUSIC_TRACKS[1].beats,
        },
      ],
      textLayers: [
        {
          id: "txt_quote",
          text: "SOME DAYS FEEL LIKE POETRY",
          timelineStart: 1.5,
          timelineEnd: 6.0,
          x: 50,
          y: 78,
          fontFamily: "Serif",
          fontSize: 16,
          color: "#F4F5F8",
          bgColor: "rgba(0,0,0,0.6)",
          animation: "fade",
          style: "subtitles",
        },
      ],
      stickers: [],
      effects: [
        {
          id: "fx_vhs",
          effect: "vhs",
          timelineStart: 0,
          timelineEnd: 12.0,
          intensity: 40,
        },
      ],
      captions: [],
      adjustments: {
        brightness: 95,
        contrast: 115,
        saturation: 85,
        exposure: -5,
        temperature: 20,
        vignette: 40,
        filterPreset: "vintage",
      },
      memeMode: false,
      memeTopText: "",
      memeBottomText: "",
    },
  },
  {
    id: "tmpl_desi_anthem",
    name: "🇮🇳 Desi Stadium Hype",
    category: "indian",
    icon: "🇮🇳",
    description: "Cricket celebration energy, dholak beat anthem, Hinglish captions & cheer SFX.",
    previewThumbnail: "/memes/cricket.jpg",
    duration: 10.0,
    project: {
      title: "Desi Cricket Anthem",
      aspectRatio: "9:16",
      duration: 10.0,
      clips: [
        {
          id: "clip_d1",
          name: "Stadium Cheers",
          sourceUrl: "/memes/cricket.jpg",
          mediaType: "image",
          duration: 5.0,
          sourceStart: 0,
          sourceEnd: 5.0,
          timelineStart: 0,
          timelineEnd: 5.0,
          speed: 1.0,
          volume: 100,
          muted: false,
          rotation: 0,
        },
        {
          id: "clip_d2",
          name: "Victory Dance",
          sourceUrl: "/memes/dog.jpg",
          mediaType: "image",
          duration: 5.0,
          sourceStart: 0,
          sourceEnd: 5.0,
          timelineStart: 5.0,
          timelineEnd: 10.0,
          speed: 1.0,
          volume: 100,
          muted: false,
          rotation: 0,
          transitionIn: { type: "spin", duration: 0.5 },
        },
      ],
      audioTracks: [
        {
          id: "aud_dholak",
          title: PRESET_MUSIC_TRACKS[2].title,
          artist: PRESET_MUSIC_TRACKS[2].artist,
          type: "music",
          sourceUrl: "synth:dholak",
          timelineStart: 0,
          duration: 10.0,
          volume: 95,
          muted: false,
          fadeIn: false,
          fadeOut: true,
          beats: PRESET_MUSIC_TRACKS[2].beats,
        },
      ],
      textLayers: [
        {
          id: "txt_india",
          text: "INDIA JEET GAYA! 🇮🇳🔥",
          timelineStart: 0.5,
          timelineEnd: 4.8,
          x: 50,
          y: 20,
          fontFamily: "Impact",
          fontSize: 28,
          color: "#F59E0B",
          strokeColor: "#000000",
          strokeWidth: 5,
          animation: "bounce",
          style: "meme_impact",
        },
      ],
      stickers: [
        {
          id: "stk_cricket",
          emojiOrUrl: "🏏",
          type: "emoji",
          timelineStart: 0.5,
          timelineEnd: 9.5,
          x: 80,
          y: 25,
          scale: 1.5,
          rotation: 15,
          animation: "bounce",
        },
      ],
      effects: [],
      captions: [
        {
          id: "cap_d1",
          text: "Pure mohalle mein mithai bantegi aaj! 🎉",
          timelineStart: 1.0,
          timelineEnd: 5.0,
          words: [
            { word: "Pure", start: 1.0, end: 1.8 },
            { word: "mohalle", start: 1.8, end: 2.6 },
            { word: "mein", start: 2.6, end: 3.2 },
            { word: "mithai!", start: 3.2, end: 4.8 },
          ],
        },
      ],
      adjustments: {
        brightness: 110,
        contrast: 120,
        saturation: 130,
        exposure: 5,
        temperature: 15,
        vignette: 10,
        filterPreset: "viral",
      },
      memeMode: false,
      memeTopText: "",
      memeBottomText: "",
    },
  },
];
