/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as BriefsRouteImport } from './routes/briefs'
import { Route as ChallengeRouteImport } from './routes/challenge'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CreateRouteImport } from './routes/create'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as HubsRouteImport } from './routes/hubs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as ReelStudioRouteImport } from './routes/reel-studio'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as YouRouteImport } from './routes/you'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiReadyRouteImport } from './routes/api.ready'
import { Route as BriefsIdRouteImport } from './routes/briefs.$id'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as HubsIdRouteImport } from './routes/hubs.$id'
import { Route as MIdRouteImport } from './routes/m.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefsRoute = BriefsRouteImport.update({
  id: '/briefs',
  path: '/briefs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeRoute = ChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const HubsRoute = HubsRouteImport.update({
  id: '/hubs',
  path: '/hubs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelStudioRoute = ReelStudioRouteImport.update({
  id: '/reel-studio',
  path: '/reel-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const YouRoute = YouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadyRoute = ApiReadyRouteImport.update({
  id: '/api/ready',
  path: '/api/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefsIdRoute = BriefsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BriefsRoute,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChatRoute,
} as any)
const HubsIdRoute = HubsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HubsRoute,
} as any)
const MIdRoute = MIdRouteImport.update({
  id: '/m/$id',
  path: '/m/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/brand': typeof BrandRoute
  '/briefs': typeof BriefsRouteWithChildren
  '/challenge': typeof ChallengeRoute
  '/chat': typeof ChatRouteWithChildren
  '/create': typeof CreateRoute
  '/editor': typeof EditorRoute
  '/hubs': typeof HubsRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/owner': typeof OwnerRoute
  '/reel-studio': typeof ReelStudioRoute
  '/reels': typeof ReelsRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/you': typeof YouRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/briefs/$id': typeof BriefsIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/hubs/$id': typeof HubsIdRoute
  '/m/$id': typeof MIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/brand': typeof BrandRoute
  '/briefs': typeof BriefsRouteWithChildren
  '/challenge': typeof ChallengeRoute
  '/chat': typeof ChatRouteWithChildren
  '/create': typeof CreateRoute
  '/editor': typeof EditorRoute
  '/hubs': typeof HubsRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/owner': typeof OwnerRoute
  '/reel-studio': typeof ReelStudioRoute
  '/reels': typeof ReelsRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/you': typeof YouRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/briefs/$id': typeof BriefsIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/hubs/$id': typeof HubsIdRoute
  '/m/$id': typeof MIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/brand': typeof BrandRoute
  '/briefs': typeof BriefsRouteWithChildren
  '/challenge': typeof ChallengeRoute
  '/chat': typeof ChatRouteWithChildren
  '/create': typeof CreateRoute
  '/editor': typeof EditorRoute
  '/hubs': typeof HubsRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/owner': typeof OwnerRoute
  '/reel-studio': typeof ReelStudioRoute
  '/reels': typeof ReelsRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/you': typeof YouRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/briefs/$id': typeof BriefsIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/hubs/$id': typeof HubsIdRoute
  '/m/$id': typeof MIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/brand'
    | '/briefs'
    | '/challenge'
    | '/chat'
    | '/create'
    | '/editor'
    | '/hubs'
    | '/login'
    | '/notifications'
    | '/owner'
    | '/reel-studio'
    | '/reels'
    | '/settings'
    | '/studio'
    | '/you'
    | '/api/health'
    | '/api/ready'
    | '/briefs/$id'
    | '/chat/$id'
    | '/hubs/$id'
    | '/m/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/brand'
    | '/briefs'
    | '/challenge'
    | '/chat'
    | '/create'
    | '/editor'
    | '/hubs'
    | '/login'
    | '/notifications'
    | '/owner'
    | '/reel-studio'
    | '/reels'
    | '/settings'
    | '/studio'
    | '/you'
    | '/api/health'
    | '/api/ready'
    | '/briefs/$id'
    | '/chat/$id'
    | '/hubs/$id'
    | '/m/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/brand'
    | '/briefs'
    | '/challenge'
    | '/chat'
    | '/create'
    | '/editor'
    | '/hubs'
    | '/login'
    | '/notifications'
    | '/owner'
    | '/reel-studio'
    | '/reels'
    | '/settings'
    | '/studio'
    | '/you'
    | '/api/health'
    | '/api/ready'
    | '/briefs/$id'
    | '/chat/$id'
    | '/hubs/$id'
    | '/m/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BrandRoute: typeof BrandRoute
  BriefsRoute: typeof BriefsRouteWithChildren
  ChallengeRoute: typeof ChallengeRoute
  ChatRoute: typeof ChatRouteWithChildren
  CreateRoute: typeof CreateRoute
  EditorRoute: typeof EditorRoute
  HubsRoute: typeof HubsRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OwnerRoute: typeof OwnerRoute
  ReelStudioRoute: typeof ReelStudioRoute
  ReelsRoute: typeof ReelsRoute
  SettingsRoute: typeof SettingsRoute
  StudioRoute: typeof StudioRoute
  YouRoute: typeof YouRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiReadyRoute: typeof ApiReadyRoute
  MIdRoute: typeof MIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefs': {
      id: '/briefs'
      path: '/briefs'
      fullPath: '/briefs'
      preLoaderRoute: typeof BriefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge': {
      id: '/challenge'
      path: '/challenge'
      fullPath: '/challenge'
      preLoaderRoute: typeof ChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hubs': {
      id: '/hubs'
      path: '/hubs'
      fullPath: '/hubs'
      preLoaderRoute: typeof HubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reel-studio': {
      id: '/reel-studio'
      path: '/reel-studio'
      fullPath: '/reel-studio'
      preLoaderRoute: typeof ReelStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/you': {
      id: '/you'
      path: '/you'
      fullPath: '/you'
      preLoaderRoute: typeof YouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ready': {
      id: '/api/ready'
      path: '/api/ready'
      fullPath: '/api/ready'
      preLoaderRoute: typeof ApiReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefs/$id': {
      id: '/briefs/$id'
      path: '/$id'
      fullPath: '/briefs/$id'
      preLoaderRoute: typeof BriefsIdRouteImport
      parentRoute: typeof BriefsRoute
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/hubs/$id': {
      id: '/hubs/$id'
      path: '/$id'
      fullPath: '/hubs/$id'
      preLoaderRoute: typeof HubsIdRouteImport
      parentRoute: typeof HubsRoute
    }
    '/m/$id': {
      id: '/m/$id'
      path: '/m/$id'
      fullPath: '/m/$id'
      preLoaderRoute: typeof MIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BriefsRouteChildren {
  BriefsIdRoute: typeof BriefsIdRoute
}

const BriefsRouteChildren: BriefsRouteChildren = {
  BriefsIdRoute: BriefsIdRoute,
}

const BriefsRouteWithChildren =
  BriefsRoute._addFileChildren(BriefsRouteChildren)

interface ChatRouteChildren {
  ChatIdRoute: typeof ChatIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIdRoute: ChatIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface HubsRouteChildren {
  HubsIdRoute: typeof HubsIdRoute
}

const HubsRouteChildren: HubsRouteChildren = {
  HubsIdRoute: HubsIdRoute,
}

const HubsRouteWithChildren = HubsRoute._addFileChildren(HubsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BrandRoute: BrandRoute,
  BriefsRoute: BriefsRouteWithChildren,
  ChallengeRoute: ChallengeRoute,
  ChatRoute: ChatRouteWithChildren,
  CreateRoute: CreateRoute,
  EditorRoute: EditorRoute,
  HubsRoute: HubsRouteWithChildren,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OwnerRoute: OwnerRoute,
  ReelStudioRoute: ReelStudioRoute,
  ReelsRoute: ReelsRoute,
  SettingsRoute: SettingsRoute,
  StudioRoute: StudioRoute,
  YouRoute: YouRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiReadyRoute: ApiReadyRoute,
  MIdRoute: MIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
